name: Update Vevor Weather Data 2

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kod
      uses: actions/checkout@v3

    - name: Python beallitasa
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Fuggosegek telepitese
      run: |
        pip install -r requirements.txt

    - name: Script futtatasa
      env:
        TUYA_ACCESS_ID: ${{ secrets.TUYA_ACCESS_ID }}
        TUYA_ACCESS_SECRET: ${{ secrets.TUYA_ACCESS_SECRET }}
        TUYA_DEVICE_ID: ${{ secrets.TUYA_DEVICE_ID }}
        WU_STATION_ID: ${{ secrets.WU_STATION_ID }}
        WU_STATION_KEY: ${{ secrets.WU_STATION_KEY }}
      run: python weather.py
